// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var AbortControllerJs = require("./abort-controller.js");

var t = AbortControllerJs.AbortSignal;

exports.t = t;
/* t Not a pure module */
