// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var AbortControllerJs = require("./abort-controller.js");

var t = AbortControllerJs.AbortController;

function make(prim) {
  return new AbortControllerJs.AbortController();
}

exports.t = t;
exports.make = make;
/* t Not a pure module */
